# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift

use_frameworks!

target 'StaticWebsiteGeneratorExample' do

#pod 'StaticWebsiteGenerator', '~> 0.0.1-beta1'
pod 'StaticWebsiteGenerator', :path => '..'

end

